name: .NET with SQL Server

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "L1mb0-m@N"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore API/ProjectIndependence/ProjectIndependence.sln

    - name: Build
      run: dotnet build API/ProjectIndependence/ProjectIndependence.sln --no-restore
     
    - name: Test
      run: dotnet test API/ProjectIndependence/ProjectIndependence.API.Tests/ProjectIndependence.API.Tests.csproj --verbosity normal
